#!/sbin/busybox sh

cd /sbin

for i in $(./busybox --list)
do
	./busybox ln -s busybox $i
done

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /dev/block
mknod /dev/block/mmcblk0p20 b 179 20
mount -t ext4 /dev/block/mmcblk0p20 /system

out() {
	umount -f /system

	chmod 755 /init
	chmod 644 /*.qcom
	chmod 644 /*.rc
	chmod 644 /*.prop
	chmod -R 755 /lib

	exec /init
}

if grep -q ro.build.version.sdk=19 /system/build.prop ; then
    mv -f /res/aosp44/* /
fi

out
